baseURL = "/"
languageCode = "ru-RU"
defaultContentLanguage = "ru"
title = "Nokhchiyn Mott Development"
theme = "anubis2"
paginate = 5

[author]
name = "NMD"
email  = "real.vladislav.grigorian@yandex.ru"
location = "Singapore"

[params]
description = "Anubis2 is another simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true

colorTheme = "auto"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
locale = "ru-RU"
math = false # true: enable mathjax globally (default is false)
toc = true

# customCSS = ["custom-css/custom1.scss", "custom-css/custom2.css"]

social = [
    { id = "github", url = "https://github.com/Junyi-99/hugo-theme-anubis2" },
    { id = "email", url = "example@example.com" },
    { id = "telegram", url = "#" }
]

[[menu.main]]
identifier = "home"
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Проекты"
url = "/projects/"
weight = 2

[[menu.main]]
identifier = "about"
name = "О нас"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Тэги"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "archive"
name = "Архив"
url = "/posts/"
weight = 5

[languages]
[languages.ru]
languageName = "Русский"

[languages.ce]
languageName = "Нохчийн"

[[languages.ce.menu.main]]
identifier = "home"
name = "Коьрта агӏор"
url = "/"
weight = 1

[[languages.ce.menu.main]]
identifier = "projects"
name = "Кхолларалла"
url = "/projects/"
weight = 2

[[languages.ce.menu.main]]
identifier = "about"
name = "Довзийтар"
url = "/about/"
weight = 3

[[languages.ce.menu.main]]
identifier = "tags"
name = "Тэгаш"
url = "/tags/"
weight = 4

[[languages.ce.menu.main]]
identifier = "archive"
name = "Жаргат"
url = "/posts/"
weight = 5

[languages.ce.params]
languageCode = "ce-ce"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'base16-snazzy'
tabWidth           = 4

#[params.UmamiAnalytics]
#enabled = true
#dnt = false
#id = "e4f661ff-9a8c-49d4-b3cc-2efe553e3973"                                            # Website ID
#datacache = false
#url = "https://eu.umami.is/script.js"
#shareUrl = "https://eu.umami.is/share/RIETUMwZn4IBMIr8/hugo-theme-anubis2.netlify.app"